### ISSUE TITLE
Transportation Census Variable Missing Data

### ISSUE THREAD

**Issue by MicheleTobias** [datalab-dev/graves-endocrine_surgeons#29]
The `estimate_population.R` file is returning reasonable results for all of the variables, except that the transportation variable is returning all zeros. We need to investigate why that is happening. Some ideas: Is it that we can't get this variable at the tract level? Is there something missing from the request? Is it something wrong with the TidyCensus package (if so, we should report the bug when we figure it out)?

As a backup plan, is there a different source for the transportation data, like getting the tables directly from the census?

**Comment by alisonsnwong** [comment]
I loaded the transportation variable from get_acs() in the tract level and block group level separately and all variables for all GEOID returned NA values.

According to the census reporter website, the data from the B08406 table (transportation) is only available country-wide at the county level. I tried anything smaller than that and there are no data for it. 

https://censusreporter.org/data/table/?table=B08406&geo_ids=050|01000US&primary_geo_id=05000US06113#valueType|estimate

**Comment by alisonsnwong** [comment]
I will start looking at other sources of transportation data.

**Comment by alisonsnwong** [comment]
B08101_001 - B08101_056 variables: MEANS OF TRANSPORTATION TO WORK BY AGE. 

These variables show results at the tract level and it is divided by age for each type of transportation. We can use the total age rows (includes all ages) for each transportation type for our analysis.

**Comment by MicheleTobias** [comment]
Thanks for investigating this! Looks like you found a good solution to work with the data we can get. I agree that county-level data isn't very useful here - compare San Bernardino County in CA with any county on the east coast!

**Comment by alisonsnwong** [comment]
Yeah, no problem. I added the new variables in the census_variables.csv.

**Comment by MicheleTobias** [comment]
Does the new data require any different analysis to aggregate the data the way we need it or does TidyCensus handle that automatically?

**Comment by alisonsnwong** [comment]
The new variables are on the same ACS 5-year data table so Tidycensus can handle it automatically as well, along with the other variables.

**Comment by MicheleTobias** [comment]
I believe we have solved this issue, but if not, please reopen it and add more information.
